### PR TITLE
Support python 3.11

### PR DESCRIPTION
**Pull request by pgarrison**
Part of #419 

## Before submitting

- [ ] Did you **test your PR locally** with `pytest` command?
- [ ] Did you **run pre-commit hooks** with `pre-commit run -a` command?

### CODE REVIEW

**Comment by pgarrison** [comment]
Tests pass on ubuntu 3.11 but time out on windows, which is a pre-existing bug #422, so I think this PR is good to go?

**Review by benjijamorris — DISMISSED** [review]

**Comment by benjijamorris** [comment]
Sweet! Thanks for doing this @pgarrison

**Comment by pgarrison** [comment]
I realize that without updating `test-requirements.txt`, these tests are running against the old dependencies.

**Comment by pgarrison** [comment]
Make requirements job seems to be failing confusingly
```
[KeyError]: 'Requires-Python'
```

**Comment by pgarrison** [comment]
This change now broke the 3.9 and 3.10 builds. I notice that the `requirements` files haven't been updated in 5 months, so it's possible that there's a bigger problem lurking.

**Comment by pgarrison** [comment]
Blocked by #424, closing for now

**Pull request closed without merging**
